Update configure-service-provider.jsp
Added the new variable maxlenght for characters written in description field. 
If there is no maximum length check of text written in description field(while we edit service provider) and when we enter the more then 1024 characters in this field it is thrown an exception in the logs while saving data in db. logs for the same is given below:
TID: [-1234] [] [2018-08-08 14:49:05,326] ERROR {org.wso2.carbon.identity.application.mgt.ApplicationManagementAdminService} -  Error while creating application: test for tenant: carbon.super 
org.wso2.carbon.identity.application.common.IdentityApplicationManagementException: Error while Creating Application
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.createApplication(ApplicationDAOImpl.java:304)
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementServiceImpl.createApplication(ApplicationManagementServiceImpl.java:140)
	at org.wso2.carbon.identity.application.mgt.ApplicationManagementAdminService.createApplication(ApplicationManagementAdminService.java:56)
Caused by: org.h2.jdbc.JdbcSQLException: Value too long for column "DESCRIPTION VARCHAR(1024)": "'abcdefghijklmnopqrstuvwxyzaabbabcdefghijklmnopqrstuvwxyzaabbabcdefghijklmnopqrstuvwxyzaabbavfrtghnjuabcdefghijklmnopqrstuvwxyza... (1200)"; SQL statement:
INSERT INTO SP_APP (TENANT_ID, APP_NAME, USER_STORE, USERNAME, DESCRIPTION, AUTH_TYPE, IS_USE_TENANT_DOMAIN_SUBJECT, ENABLE_AUTHORIZATION,IS_USE_USER_DOMAIN_SUBJECT) VALUES (?,?,?,?,?,?,?,?,?) [22001-175]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:332)
	at org.h2.message.DbException.get(DbException.java:172)
	at org.wso2.carbon.identity.application.mgt.dao.impl.ApplicationDAOImpl.createApplication(ApplicationDAOImpl.java:265)